INSERT ALL
    INTO EMPLOYEE (SURMANE, NAME, PATRONYMIC, SEX, BIRTH_DATE, EMPLOYMENT_DATE, SALARY, CHILDREN_NUMBER, DEPARTMENT_ID, CREW_ID) VALUES ('Ivanov', 'Petr', 'Danilovich', 'M', TO_DATE('1976/05/03', 'yyyy/mm/dd'), TO_DATE('2021/09/23', 'yyyy/mm/dd'), 12435.24, 1, 1, NULL)
SELECT 1 FROM DUAL
