CREATE TABLE EMPLOYEE (
    ID INT NOT NULL,
    SURNAME VARCHAR2(255) NOT NULL,
    NAME VARCHAR2(255) NOT NULL,
    PATRONYMIC VARCHAR2(255) NOT NULL,
    SEX CHAR(1) CHECK (SEX IN ('M','F')) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    EMPLOYMENT_DATE DATE NOT NULL,
    SALARY FLOAT NOT NULL,
    CHILDREN_NUMBER INT NOT NULL,
    DEPARTMENT_ID INT NOT NULL,
    CREW_ID INT,
    CONSTRAINT EMPLOYEE_PK PRIMARY KEY (ID),
    CONSTRAINT EMPLOYEE_FK0 FOREIGN KEY (DEPARTMENT_ID) REFERENCES Department(ID),
    CONSTRAINT EMPLOYEE_FK1 FOREIGN KEY (CREW_ID) REFERENCES Crew(ID)
)