ALTER TABLE AIRPLANE_MAINTENANCE_HISTORY
    ADD CONSTRAINT AIRPLANE_MAINTENANCE_HIST_fk0 FOREIGN KEY (maintenance_type_id) REFERENCES MAINTENANCE_TYPE (maintenance_type_id);
ALTER TABLE AIRPLANE_MAINTENANCE_HISTORY
    ADD CONSTRAINT AIRPLANE_MAINTENANCE_HIST_fk1 FOREIGN KEY (airplane_id) REFERENCES AIRPLANE (airplane_id);
ALTER TABLE AIRPLANE_MAINTENANCE_HISTORY
    ADD CONSTRAINT AIRPLANE_MAINTENANCE_HIST_fk2 FOREIGN KEY (crew_id) REFERENCES CREW (crew_id);