ALTER TABLE AIRPLANE
    ADD CONSTRAINT AIRPLANE_fk0 FOREIGN KEY (airplane_type_id) REFERENCES AIRPLANE_TYPE (airplane_type_id);
ALTER TABLE AIRPLANE
    ADD CONSTRAINT AIRPLANE_fk1 FOREIGN KEY (pilot_crew_id) REFERENCES CREW (crew_id);
ALTER TABLE AIRPLANE
    ADD CONSTRAINT AIRPLANE_fk2 FOREIGN KEY (technical_crew_id) REFERENCES CREW (crew_id);
ALTER TABLE AIRPLANE
    ADD CONSTRAINT AIRPLANE_fk3 FOREIGN KEY (service_crew_id) REFERENCES CREW (crew_id);
ALTER TABLE AIRPLANE
    ADD CONSTRAINT AIRPLANE_fk4 FOREIGN KEY (airport_location_id) REFERENCES LOCATION (location_id);
