ALTER TABLE AIRPLANE
    ADD CONSTRAINT AIRPLANE_FK0 FOREIGN KEY (airplane_type_id) REFERENCES AIRPLANE_TYPE (airplane_type_id);
ALTER TABLE AIRPLANE
    ADD CONSTRAINT AIRPLANE_FK1 FOREIGN KEY (pilot_crew_id) REFERENCES CREW (crew_id);
ALTER TABLE AIRPLANE
    ADD CONSTRAINT AIRPLANE_FK2 FOREIGN KEY (technical_crew_id) REFERENCES CREW (crew_id);
ALTER TABLE AIRPLANE
    ADD CONSTRAINT AIRPLANE_FK3 FOREIGN KEY (service_crew_id) REFERENCES CREW (crew_id);
ALTER TABLE AIRPLANE
    ADD CONSTRAINT AIRPLANE_FK4 FOREIGN KEY (airport_location_id) REFERENCES LOCATION (location_id);
