ALTER TABLE CASHIER
    ADD CONSTRAINT CASHIER_FK0 FOREIGN KEY (cashier_id) REFERENCES EMPLOYEE (employee_id);
ALTER TABLE CASHIER
    ADD CONSTRAINT CASHIER_FK1 FOREIGN KEY (cashier_work_direction_id) REFERENCES CASHIER_WORK_DIRECTION (work_direction_id);