ALTER TABLE CASHIER
    ADD CONSTRAINT CASHIER_fk0 FOREIGN KEY (cashier_id) REFERENCES EMPLOYEE (employee_id);
ALTER TABLE CASHIER
    ADD CONSTRAINT CASHIER_fk1 FOREIGN KEY (cashier_work_direction_id) REFERENCES CASHIER_WORK_DIRECTION (work_direction_id);