ALTER TABLE DEPARTURE_STATUS_HISTORY
    ADD CONSTRAINT DEPARTURE_STATUS_HISTORY_fk0 FOREIGN KEY (departure_id) REFERENCES DEPARTURE (departure_id);

ALTER TABLE DEPARTURE_STATUS_HISTORY
    ADD CONSTRAINT DEPARTURE_STATUS_HISTORY_fk1 FOREIGN KEY (status_id) REFERENCES DEPARTURE_STATUS (departure_status_id);