ALTER TABLE DIRECTOR
    ADD CONSTRAINT DIRECTOR_FK0 FOREIGN KEY (director_id) REFERENCES EMPLOYEE (employee_id);
ALTER TABLE DIRECTOR
    ADD CONSTRAINT DIRECTOR_FK1 FOREIGN KEY (eng_level_id) REFERENCES ENG_LEVEL (eng_level_id);