ALTER TABLE DISPATCHER
    ADD CONSTRAINT DISPATCHER_FK0 FOREIGN KEY (dispatcher_id) REFERENCES EMPLOYEE (employee_id);
ALTER TABLE DISPATCHER
    ADD CONSTRAINT DISPATCHER_FK1 FOREIGN KEY (dispatcher_work_direction_id) REFERENCES DISPATCHER_WORK_DIRECTION (work_direction_id);