ALTER TABLE EMPLOYEE
    ADD CONSTRAINT EMPLOYEE_FK0 FOREIGN KEY (department_id) REFERENCES DEPARTMENT (department_id);
ALTER TABLE EMPLOYEE
    ADD CONSTRAINT EMPLOYEE_FK1 FOREIGN KEY (crew_id) REFERENCES CREW (crew_id);
ALTER TABLE EMPLOYEE
    ADD CONSTRAINT EMPLOYEE_FK2 FOREIGN KEY (specialty_id) REFERENCES SPECIALIZATION (specialty_id);