ALTER TABLE EMPLOYEE
    ADD CONSTRAINT EMPLOYEE_fk0 FOREIGN KEY (department_id) REFERENCES DEPARTMENT (department_id);
ALTER TABLE EMPLOYEE
    ADD CONSTRAINT EMPLOYEE_fk1 FOREIGN KEY (crew_id) REFERENCES CREW (crew_id);
ALTER TABLE EMPLOYEE
    ADD CONSTRAINT EMPLOYEE_fk2 FOREIGN KEY (specialty_id) REFERENCES SPECIALTY (specialty_id);