ALTER TABLE OPERATOR
    ADD CONSTRAINT OPERATOR_fk0 FOREIGN KEY (operator_Id) REFERENCES EMPLOYEE (employee_id);
ALTER TABLE OPERATOR
    ADD CONSTRAINT OPERATOR_fk1 FOREIGN KEY (operator_work_direction_id) REFERENCES OPERATOR_WORK_DIRECTION (work_direction_id);