ALTER TABLE PILOT
    ADD CONSTRAINT PILOT_fk0 FOREIGN KEY (pilot_id) REFERENCES EMPLOYEE (employee_id);
ALTER TABLE PILOT
    ADD CONSTRAINT PILOT_fk1 FOREIGN KEY (eng_level_id) REFERENCES ENG_LEVEL (eng_level_id);