ALTER TABLE SECURITY_OFFICER
    ADD CONSTRAINT SECURITY_OFFICER_fk0 FOREIGN KEY (security_officer_id) REFERENCES EMPLOYEE (employee_id);
ALTER TABLE SECURITY_OFFICER
    ADD CONSTRAINT SECURITY_OFFICER_fk1 FOREIGN KEY (security_work_direction_id) REFERENCES SECURITY_WORK_DIRECTION (work_direction_id);