ALTER TABLE TECHNICIAN
    ADD CONSTRAINT TECHNICIAN_fk0 FOREIGN KEY (technician_id) REFERENCES EMPLOYEE (employee_id);
ALTER TABLE TECHNICIAN
    ADD CONSTRAINT TECHNICIAN_fk1 FOREIGN KEY (technician_work_direction_id) REFERENCES TECHNICIAN_WORK_DIRECTION (work_direction_id);