ALTER TABLE TICKET
    ADD CONSTRAINT TICKET_FK0 FOREIGN KEY (departure_id) REFERENCES DEPARTURE (departure_id);
ALTER TABLE TICKET
    ADD CONSTRAINT TICKET_FK1 FOREIGN KEY (ticket_status_id) REFERENCES TICKET_STATUS (ticket_status_id);