ALTER TABLE TICKET_STATUS_HISTORY
    ADD CONSTRAINT TICKET_STATUS_HISTORY_FK0 FOREIGN KEY (ticket_status_id) REFERENCES TICKET_STATUS (ticket_status_id);
ALTER TABLE TICKET_STATUS_HISTORY
    ADD CONSTRAINT TICKET_STATUS_HISTORY_FK1 FOREIGN KEY (passenger_id) REFERENCES PASSENGER (passenger_id);