ALTER TABLE TICKET_STATUS_HISTORY
    ADD CONSTRAINT TICKET_STATUS_HISTORY_fk0 FOREIGN KEY (departure_id) REFERENCES TICKET (departure_id);
ALTER TABLE TICKET_STATUS_HISTORY
    ADD CONSTRAINT TICKET_STATUS_HISTORY_fk1 FOREIGN KEY (seat) REFERENCES TICKET (seat);
ALTER TABLE TICKET_STATUS_HISTORY
    ADD CONSTRAINT TICKET_STATUS_HISTORY_fk2 FOREIGN KEY (ticket_status_id) REFERENCES TICKET_STATUS (ticket_status_id);